### ISSUE TITLE
join(): Passing glue string after array is deprecated. Swap the parameters (View: C:\vendor\log-viewer\bootstrap-4\show.blade.php)

### ISSUE THREAD

**Issue by stonkeep** [ARCANEDEV/LogViewer#358]
- LogViewer Version: 7.0.0

Environment information
Laravel version
7.22.4
Laravel locale
pt-BR
Laravel config cached
false
PHP version
7.4.7

### Description:
Entring in http://127.0.0.1:8000/log-viewer/logs/2020-07-29 

### Steps To Reproduce:

![image](https://user-images.githubusercontent.com/3990028/88843726-f6ea6c00-d1b7-11ea-9284-377984123f54.png)

**Comment by arcanedev-maroc** [comment]
The issue was fixed in: #317 

You need to update the old published views or delete the `resources\views\vendor\log-viewer` folder if you didn't edit the them

**Comment by manojo123** [comment]
Same problem here.. Deleted the resources\views\vendor\log-viewer and the error persists. consider

**Comment by narenderwaraich** [comment]
same problem on live server https://mynearfood.in/logs/logs/2021-09-10/error show log but not show log detail's

**Comment by Sirajunnasihin** [comment]
just change this code in show.blade.php from

`join(log_styler()->toHighlight(), '|')`

Changes to

`join('|', log_styler()->toHighlight())`

**Comment by guruskid** [comment]
https://dev.to/guruskid/laravel-real-time-log-monitoring-1l81

**Comment by guruskid** [comment]
> The issue was fixed in: #317
> 
> You need to update the old published views or delete the `resources\views\vendor\log-viewer` folder if you didn't edit them

check this link https://dev.to/guruskid/laravel-real-time-log-monitoring-1l81
